apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodereal-default
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: image-pull
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYm5iLXBrZyIsInBhc3N3b3JkIjoiZ2hwX2tlSnhVVno1T0JWTDA5MmZ3N3JFR1BVemJSYzFObTNVdVNDbyIsImF1dGgiOiJZbTVpTFhCclp6cG5hSEJmYTJWS2VGVldlalZQUWxaTU1Ea3labmMzY2tWSFVGVjZZbEpqTVU1dE0xVjFVME52In19fQ==

