apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodereal-default
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: image-pull
data:
  .dockerconfigjson: your-secret-here

