resources:
  - https://github.com/node-real/greenfield-sp-k8s/base/vendors/aws/large?ref=v0.4.11  # check doco for latest version

configMapGenerator:
- name: config
  files:
  - ./config.toml  # check and replace values in this config file

images:
- name: ghcr.io/bnb-chain/greenfield-storage-provider
  newTag: 0.2.3-alpha.15  # check doco for latest version

patches:
- target:
    kind: ServiceAccount
    name: sp-default
  patch: |-
    - op: replace
      path: "/metadata/annotations/eks.amazonaws.com~1role-arn"
      value: arn:aws:iam::111111111111:role/your-iam-role-mapped-to-k8s-sa  # replace with your IAM role

# to update CORS header
- target:
    kind: Ingress
    name: gateway
  path: ./nginx_cors_headers.yaml

- target:
    kind: Ingress
    name: gateway
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: yourdomain.com  # replace with your domain name
    - op: replace
      path: /spec/rules/1/host
      value: "*.yourdomain.com"  # replace with your domain name

# the followings are for AWS secret manager. you can ignore use can create opaque secret too
- target:
    kind: SecretStore
    name: default
  patch: |-
    - op: replace
      path: /spec/provider/aws/region
      value: us-east-1  # replace with your region
- target:
    kind: ExternalSecret
    name: default
  patch: |-
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: secret-key   # replace with your secret key

# required to export metrics
- target:
    kind: ServiceMonitor
    name: default
  patch: |-
    - op: replace
      path: /spec/namespaceSelector/matchNames/0
      value: yournamespace  # replace with your k8s namespace

