# This file configures github.com/golangci/golangci-lint.

run:
  concurrency: 4
  timeout: 5m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
#    - depguard
#    - dogsled
#    - exportloopref
#    - gocritic
#    - gofumpt
#    - gosec
#    - nakedret
#    - nolintlint
#    - stylecheck
#    - typecheck

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences
