chain:
  prefix: "cosmos"
  modules:
node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://localhost:26750
      max_connections: 20
    grpc:
      insecure: true
      address: http://localhost:9090
parsing:
  fast_sync: false
  listen_new_blocks: true
  parse_genesis: true
  parse_old_blocks: true
  start_height: 1
  workers: 1
database:
  url: postgres://postgres:1q2w3e4r*@localhost:5432/juno-use?sslmode=disable&search_path=public
logging:
  format: "text"
  level: "debug"
