apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: uploader
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uploader
    spec:
      serviceAccountName: sp-default
      containers:
      - name: uploader
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.3
        args: ["--log.std", "-c", "/config/config.toml", "-server", "uploader"]
        env:
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY
                name: default
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_KEY
                name: default
          - name: AWS_SESSION_TOKEN
            value: ""
          - name: SP_DB_USER
            valueFrom:
              secretKeyRef:
                key: SP_DB_USER
                name: default
          - name: SP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SP_DB_PASSWORD
                name: default
          - name: SP_DB_ADDRESS
            valueFrom:
              secretKeyRef:
                key: SP_DB_ADDRESS
                name: default
          - name: BUCKET_URL
            valueFrom:
              secretKeyRef:
                key: BUCKET_URL
                name: default
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        ports:
          - containerPort: 9333
            name: uploader
          - containerPort: 24367
            name: metrics
          - containerPort: 24368
            name: pprof
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: uploader
spec:
  ports:
  - port: 9333
    targetPort: 9333
    name: uploader
  - port: 24367
    targetPort: 24367
    name: metrics
  - port: 24368
    targetPort: 24368
    name: pprof
  selector:
    app: uploader
