apiVersion: apps/v1
kind: Deployment
metadata:
  name: signer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signer
  template:
    metadata:
      labels:
        app: signer
    spec:
      serviceAccountName: nodereal-default
      containers:
      - name: signer
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.3
        args: ["--log.std", "-c", "/config/config.toml", "-server", "signer"]
        env:
          - name: SP_DB_USER
            valueFrom:
              secretKeyRef:
                key: SP_DB_USER
                name: default
          - name: SP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SP_DB_PASSWORD
                name: default
          - name: SP_DB_ADDRESS
            valueFrom:
              secretKeyRef:
                key: SP_DB_ADDRESS
                name: default
          - name: SIGNER_OPERATOR_PRIV_KEY
            valueFrom:
              secretKeyRef:
                key: SIGNER_OPERATOR_PRIV_KEY
                name: default
          - name: SIGNER_FUNDING_PRIV_KEY
            valueFrom:
              secretKeyRef:
                key: SIGNER_FUNDING_PRIV_KEY
                name: default
          - name: SIGNER_APPROVAL_PRIV_KEY
            valueFrom:
              secretKeyRef:
                key: SIGNER_APPROVAL_PRIV_KEY
                name: default
          - name: SIGNER_SEAL_PRIV_KEY
            valueFrom:
              secretKeyRef:
                key: SIGNER_SEAL_PRIV_KEY
                name: default
          - name: SIGNER_GC_PRIV_KEY
            valueFrom:
              secretKeyRef:
                key: SIGNER_GC_PRIV_KEY
                name: default
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        ports:
          - containerPort: 9333
            name: signer
          - containerPort: 24367
            name: metrics
          - containerPort: 24368
            name: pprof
        volumeMounts:
        - mountPath: /config
          name: config
      imagePullSecrets:
        - name: image-pull
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: signer
spec:
  ports:
  - port: 9333
    targetPort: 9333
    name: signer
  - port: 24367
    targetPort: 24367
    name: metrics
  - port: 24368
    targetPort: 24368
    name: pprof
  selector:
    app: signer
---
