Service = ["gateway", "uploader", "downloader", "challenge", "tasknode", "receiver", "signer", "blocksyncer", "metadata", "manager", "auth"]
SpOperatorAddress = "677265656e6669656c642d73746f726167652d70726f7669646572"

[Endpoint]
challenge = "localhost:9333"
downloader = "localhost:9233"
gateway = "gnfd.sp.com"
metadata = "localhost:9733"
p2p = "localhost:9833"
receiver = "localhost:9533"
signer = "localhost:9633"
tasknode = "localhost:9433"
uploader = "localhost:9133"
auth = "localhost:10033"

[ListenAddress]
challenge = "localhost:9333"
downloader = "localhost:9233"
gateway = "localhost:9033"
metadata = "localhost:9733"
p2p = "localhost:9833"
receiver = "localhost:9533"
signer = "localhost:9633"
tasknode = "localhost:9433"
uploader = "localhost:9133"
auth = "localhost:10033"

[SpDBConfig]
User = "root"
Passwd = "test_pwd"
Address = "localhost:3306"
Database = "storage_provider_db"

[PieceStoreConfig]
Shards = 0

[PieceStoreConfig.Store]
Storage = "file"
BucketURL = "./data"
MaxRetries = 5
MinRetryDelay = 0
TLSInsecureSkipVerify = false
IAMType = "AKSK"

[ChainConfig]
ChainID = "greenfield_9000-1741"

[[ChainConfig.NodeAddr]]
GreenfieldAddresses = ["localhost:9090"]
TendermintAddresses = ["http://localhost:26750"]

[SignerCfg]
WhitelistCIDR = ["0.0.0.0/0"]
GasLimit = 210000
OperatorPrivateKey = ""
FundingPrivateKey = ""
SealPrivateKey = ""
ApprovalPrivateKey = ""

[BlockSyncerCfg]
Modules = ["epoch", "bucket", "object", "payment"]
Dsn = "localhost:3308"

[P2PCfg]
ListenAddress = "127.0.0.1:9833"
P2PPrivateKey = ""
Bootstrap = []
PingPeriod = 2

[MetricsCfg]
Enabled = false
HTTPAddress = "localhost:24036"

[LogCfg]
Level = "debug"
Path = "./gnfd-sp.log"

[RateLimiter]
APILimits = [{Key = "localhost:9033-/", RateLimit = 10, RatePeriod = "S"},]
HostPattern = [
    {Key = "^[a-z0-9][a-z0-9\\.\\-]{1,61}[a-z0-9].localhost:9033$", RateLimit = 1, RatePeriod = "S"},
]
PathPattern = [
    {Key = "^/[^/]+/?$", RateLimit = 1, RatePeriod = "S"},
]
[RateLimiter.HTTPLimitCfg]
On = false
RateLimit = 1
RatePeriod = "S"
