Service = [
    "BlockSyncer",
    #"Gateway", "Uploader", "Downloader", "StoneHub", "StoneNode", "Syncer", "Signer","Challenge",
]

[GatewayCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9033"
    Domain = "gnfd.nodereal.com"
    UploaderServiceAddress = "127.0.0.1:9133"
    DownloaderServiceAddress = "127.0.0.1:9233"
    ChallengeServiceAddress = "127.0.0.1:9633"


[UploaderCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9133"
    StoneHubServiceAddress = "127.0.0.1:9333"
    MetaDBType = "leveldb"
    [UploaderCfg.PieceStoreConfig]
        Shards = 0
        [UploaderCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true
    [UploaderCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[DownloaderCfg]
    Address = "127.0.0.1:9233"
    [DownloaderCfg.PieceStoreConfig]
        Shards = 0
        [DownloaderCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true

[StoneHubCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9333"
    JobDBType = "memory"
    MetaDBType = "leveldb"
    [StoneHubCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false


[StoneNodeCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9433"
    StoneHubServiceAddress = "127.0.0.1:9333"
    SyncerServiceAddress = ["127.0.0.1:9543", "127.0.0.1:9553", "127.0.0.1:9563", "127.0.0.1:9573", "127.0.0.1:9583", "127.0.0.1:9593"]
    StoneJobLimit = 64
    [StoneNodeCfg.PieceConfig]
        Shards = 0
        [StoneNodeCfg.PieceConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true

[SyncerCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9533"
    MetaDBType = "leveldb"
    [SyncerCfg.PieceConfig.Store]
        Storage = "file"
        BucketURL = "./data/secondary_payload_data"
        MaxRetries = 5
        TestMode = true
    [SyncerCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[SignerCfg]
    Address = "127.0.0.1:9633"
    WhitelistCIDR = ["127.0.0.1/32","10.0.0.0/8","172.16.0.0/12","192.168.0.0/16"]
    APIKey = ""
    [SignerCfg.GreenfieldChainConfig]
        GRPCAddr = "localhost:9090"
        ChainID = "greenfield_9000-121"
        GasLimit = 210000
        OperatorPrivateKey = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"
        FundingPrivateKey  = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"
        SealPrivateKey     = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"
        ApprovalPrivateKey = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"

[ChallengeCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9633"
    MetaDBType = "leveldb"
    [ChallengeCfg.PieceStoreConfig]
        Shards = 0
        [ChallengeCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true
    [ChallengeCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[BlockSyncerCfg]
    [BlockSyncerCfg.Chain]
    bech32_prefix = "cosmos"
    [BlockSyncerCfg.Node]
    type = "remote"
    [BlockSyncerCfg.Node.Details.Rpc]
    client_name = "juno"
    address = "http://localhost:26750"
    max_connections = 20
    [BlockSyncerCfg.Node.Details.Grpc]
    insecure = true
    address = "http://localhost:9090"
    [BlockSyncerCfg.Parsing]
    fast_sync = true
    parse_new_blocks = true
    parse_genesis = true
    parse_old_blocks = true
    start_height = 1
    workers = 1
    [BlockSyncerCfg.Database]
    type = "mysql"
    dsn = "root:1q2w3e4r*@tcp(localhost:3306)/greenfiled?parseTime=true&multiStatements=true&loc=Local"
    partition_size = 10_000
    max_idle_connections = 1
    max_open_connections = 1
    [BlockSyncerCfg.Logging]
    level = "debug"

