Service = [
    "StoneHub", "Gateway", "Uploader", "StoneNode", "Syncer",
]


[StoneHubCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:5323"
    [StoneHubCfg.MockConfig]
        Mock = true
        JobDB = "memdb"
        MetaDB = "memdb"


[GatewayCfg]
    Address = "127.0.0.1:5310"
    Domain = "bfs.nodereal.com"
    [GatewayCfg.LogConfig]
        FilePath = "./debug/gateway.log"
        Level = "info"
    [GatewayCfg.UploaderConfig]
        #Mode = "DebugMode"
        Mode = "GrpcMode"
        DebugDir = "./debug"
        Address = "127.0.0.1:5311"
    [GatewayCfg.ChainConfig]
        Mode = "DebugMode"
        DebugDir = "./debug"
    [GatewayCfg.DownloaderConfig]
        Mode = "DebugMode"
        DebugDir = "./debug"


[UploaderCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:5311"
    [UploaderCfg.LogConfig]
        FilePath = "./debug/uploader.log"
        Level = "info"
    [UploaderCfg.StoneHubConfig]
        Address = "127.0.0.1:5323"
        TimeoutSec = 5
    [UploaderCfg.PieceStoreConfig]
        Shards = 0
        [UploaderCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./debug"
            AccessKey = "ACCESSKEY"
            SecretKey = "SECRETKEY"
            SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            MaxRetries = 5
            TlsInsecureSkipVerify = false


[StoneNodeCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:5325"
    StoneHubServiceAddress = "127.0.0.1:5323"
    SyncerServiceAddress = "127.0.0.1:5324"
    [StoneNodeCfg.PieceConfig]
        Shards = 0
        [StoneNodeCfg.PieceConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-bsc-storage
            AccessKey = ""
            SecretKey = ""
            SessionToken = ""
            NoSignRequest = false
            MaxRetries = 5
            TlsInsecureSkipVerify = false


[SyncerCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:5324"
    [SyncerCfg.PieceConfig]
        Shards = 0
        [SyncerCfg.PieceConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-bsc-storage"
            AccessKey = ""
            SecretKey = ""
            SessionToken = ""
            NoSignRequest = false
            MaxRetries = 5
            TlsInsecureSkipVerify = false
