Service = [
    "blocksyncer",
]

[BlockSyncerCfg]
    [BlockSyncerCfg.Chain]
    Bech32Prefix = "cosmos"
    Modules = [ "epoch", "bucket", "object", "payment", ]

[BlockSyncerCfg.Node]
    Type = "remote"
    [BlockSyncerCfg.Node.RPC]
        ClientName = "juno"
        Address = "http://localhost:26750"
        MaxConnections = 20
    [BlockSyncerCfg.Node.GRPC]
        Insecure = true
        Address = "http://localhost:9090"

    [BlockSyncerCfg.Parser]
        FastSync = false
        ParseGenesis = true
        ParseOldBlocks = true
        ParseNewBlocks = true
        StartHeight = 1
        Workers = 1

    [BlockSyncerCfg.Database]
        Type = "mysql"
        PartitionSize = 10_000
        MaxIdleConnections = 1
        MaxOpenConnections = 1

    [BlockSyncerCfg.Logging]
        Level = "debug"