Service = [
    "Gateway", "Uploader", "Downloader", "StoneHub", "StoneNode", "Syncer", "Signer","Challenge", "Metadata",
]

[GatewayCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9033"
    Domain = "gnfd.nodereal.com"
    UploaderServiceAddress = "127.0.0.1:9133"
    DownloaderServiceAddress = "127.0.0.1:9233"
    SyncerServiceAddress = "127.0.0.1:9533"
    ChallengeServiceAddress = "127.0.0.1:9633"


[UploaderCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9133"
    StoneHubServiceAddress = "127.0.0.1:9333"
    MetaDBType = "leveldb"
    [UploaderCfg.PieceStoreConfig]
        Shards = 0
        [UploaderCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            NoSignRequest = false
            MaxRetries = 5
            TestMode = true
    [UploaderCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[DownloaderCfg]
    Address = "127.0.0.1:9233"
    [DownloaderCfg.PieceStoreConfig]
        Shards = 0
        [DownloaderCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            NoSignRequest = false
            MaxRetries = 5
            TestMode = true

[StoneHubCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9333"
    JobDBType = "memory"
    MetaDBType = "leveldb"
    [StoneHubCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[StoneNodeCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9433"
    GatewayAddress = ["127.0.0.1:9034", "127.0.0.1:9035", "127.0.0.1:9036", "127.0.0.1:9037", "127.0.0.1:9038", "127.0.0.1:9039"]
    StoneHubServiceAddress = "127.0.0.1:9333"
    StoneJobLimit = 64
    [StoneNodeCfg.PieceStoreConfig]
        Shards = 0
        [StoneNodeCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            NoSignRequest = false
            MaxRetries = 5
            TestMode = true

[SyncerCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9533"
    MetaDBType = "leveldb"
    [SyncerCfg.PieceStoreConfig.Store]
        Storage = "file"
        BucketURL = "./data/secondary_payload_data"
        NoSignRequest = false
        MaxRetries = 5
        TestMode = true
    [SyncerCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[SignerCfg]
    Address = "127.0.0.1:9633"
    WhitelistCIDR = ["127.0.0.1/32","10.0.0.0/8","172.16.0.0/12","192.168.0.0/16"]
    APIKey = ""
    [SignerCfg.GreenfieldChainConfig]
        GRPCAddr = "localhost:9090"
        ChainID = "greenfield_9000-121"
        GasLimit = 210000
        OperatorPrivateKey = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"
        FundingPrivateKey  = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"
        SealPrivateKey     = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"
        ApprovalPrivateKey = "d710d9e03466d6236d1ac2e70712b1e2ed7324b1d7f233f8887d3a703626fb9f"

[ChallengeCfg]
    StorageProvider = "gnfd-test-sp"
    Address = "127.0.0.1:9733"
    MetaDBType = "leveldb"
    [ChallengeCfg.PieceStoreConfig]
        Shards = 0
        [ChallengeCfg.PieceStoreConfig.Store]
            Storage = "file"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true
    [ChallengeCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false

[MetadataCfg]
    Address = "127.0.0.1:9733"
    MetaDBType = "sqldb"
    [MetadataCfg.MetaSqlDBConfig]
        User = "root"
        Passwd = "test_pwd"
        Address = "127.0.0.1:3306"
        Database = "meta_db"
