Port = "9090"
Domain = "bfs.nodereal.com"

[LogConfig]
FilePath = "./gateway_debug/gateway.log"
Level = "info"

[UploaderConfig]
#Mode = "DebugMode"
Mode = "GrpcMode"
DebugDir = "./gateway_debug"
GrpcAddr = "127.0.0.1:9091"

[ChainConfig]
Mode = "DebugMode"
DebugDir = "./gateway_debug"

[DownloaderConfig]
Mode = "DebugMode"
DebugDir = "./gateway_debug"