[PieceStore]
Shards = 0

[PieceStore.Store]
Storage = "file"
BucketURL = "./local_store"
AccessKey = "ACCESSKEY"
SecretKey = "SECRETKEY"
SessionToken = "SESSIONTOKEN"
NoSignRequest = false
MaxRetries = 5
TlsInsecureSkipVerify = false

[Log]
FilePath = "./logs"
Level = "debug"
MaxBytesSize = 10240000