apiVersion: v1
kind: ServiceAccount
metadata:
  name: sp-default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - null
  selector:
    matchLabels:
      team: greenfield
      biz: storage-provider

