apiVersion: v1
kind: ServiceAccount
metadata:
  name: sp-default
  annotations:
    eks.amazonaws.com/role-arn: null
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: null
      auth:
        jwt:
          serviceAccountRef:
            name: sp-default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: default
  target:
    name: default
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: null
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - null
  selector:
    matchLabels:
      team: greenfield
      biz: storage-provider

