name: Lint Commit Messages

on:
  push:
    branches:
      - master
      - develop
      - release*

  pull_request:
    branches:
      - master
      - develop
      - release*

jobs:
  commit-lint:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Deps
        run: |
          npm install -g commitlint-plugin-function-rules @commitlint/cli
          npm install --save-dev commitlint-plugin-function-rules @commitlint/cli

      - uses: wagoid/commitlint-github-action@v5
        id: commitlint
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          configFile: /github/workspace/.github/commitlint.config.js

  branch-naming-rules:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\-([a-z])+'
          allowed_prefixes: 'build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test'
          ignore: master,develop,release
          min_length: 5
          max_length: 30