name: Docker-CI

on:
  push:
    branches: [ develop, master, feat-sp-hotfix-v1.10.1-tag]

env:
  IMAGE_NAME: ghcr.io/bnb-chain/greenfield-storage-provider-invisible
  IMAGE_SOURCE: https://github.com/bnb-chain/greenfield-storage-provider

jobs:
  # Push image to GitHub Packages.
  push:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.14.0
        with:
          version: 1.14.0
          buf_user: "${{ secrets.BUF_REGISTRY_USER }}"
          buf_api_token: "${{ secrets.BUF_REGISTRY_SECRET }}"

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - run: |
          make install-tools
          make buf-gen

      - name: Build image
        run: |
          docker build . \
          --build-arg "GH_TOKEN=${{ secrets.GH_SECRET }}" \
          --label "org.opencontainers.image.source=${IMAGE_SOURCE}" \
          --label "org.opencontainers.image.revision=$(git rev-parse HEAD)" \
          --label "org.opencontainers.image.licenses=LGPL-3.0,GPL-3.0" \
          -f ./Dockerfile -t "${IMAGE_NAME}"
          
          docker build . \
          --build-arg "GH_TOKEN=${{ secrets.GH_SECRET }}" \
          --label "org.opencontainers.image.source=${IMAGE_SOURCE}" \
          --label "org.opencontainers.image.revision=$(git rev-parse HEAD)" \
          --label "org.opencontainers.image.licenses=LGPL-3.0,GPL-3.0" \
          -f ./Dockerfile.distroless -t "${IMAGE_NAME}:distroless"

      - name: Log into registry
        run: echo "${{ secrets.GH_SECRET }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          VERSION=$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          docker tag ${IMAGE_NAME}:distroless $IMAGE_NAME:$VERSION-distroless
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION-distroless
