name: Protobuf Lint

on:
  push:
    paths:
      - 'proto/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'proto/**'

jobs:
  proto-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.11.0

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'

  proto-lint-success:
    needs: proto-lint
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on success
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: dylan-yong-zhaoyu
          SLACK_USERNAME: SP Protobuf Lint
          SLACK_ICON_EMOJI: ':white_check_mark:'
          SLACK_COLOR: good
          SLACK_MESSAGE: SP protobuf lint passed on develop
          SLACK_FOOTER: ''

  proto-lint-failure:
    needs: proto-lint
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on failure
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: dylan-yong-zhaoyu
          SLACK_USERNAME: SP Protobuf Lint
          SLACK_ICON_EMOJI: ':skull:'
          SLACK_COLOR: danger
          SLACK_MESSAGE: SP protobuf lint failed on develop
          SLACK_FOOTER: ''