name: Protobuf Lint

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'proto/**'

  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'proto/**'

jobs:
  proto-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.14.0
        with:
          version: 1.14.0
          buf_user: "${{ secrets.BUF_REGISTRY_USER }}"
          buf_api_token: "${{ secrets.BUF_REGISTRY_SECRET }}"

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
