name: Protobuf Lint

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'proto/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'proto/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.8.0

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'