name: Unit Test

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'test/**'

  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - 'test/**'

jobs:
  unit-test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: ory/build-buf-action@v0
        with:
          bufVersion: v1.11.0
          protocPlugins:
            go@v1.28.0 go-grpc@v1.2.0
          bufArgs:
            generate

      - name: Unit Test
        run: |
          make test

  unit-test-success:
    needs: unit-test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on success
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: gnfd_storage_ci_cd
          SLACK_USERNAME: SP Unit Test
          SLACK_ICON_EMOJI: ':white_check_mark:'
          SLACK_COLOR: good
          SLACK_MESSAGE: Greenfield SP unit test passed
          SLACK_FOOTER: ''

  unit-test-failure:
    needs: unit-test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on failure
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: gnfd_storage_ci_cd
          SLACK_USERNAME: SP Unit Test
          SLACK_ICON_EMOJI: ':skull:'
          SLACK_COLOR: danger
          SLACK_MESSAGE: Greenfield SP unit test failed
          SLACK_FOOTER: ''